export class SolicitudPago {
  constructor({ ID_SOLICITUD, ID_FUNDACION, ID_ADMIN, ID_REPORTE, MONTO, DESCRIPCION, ESTADO, FECHA_SOLICITUD, FECHA_APROBACION, FECHA_PAGO, OBSERVACIONES, REFERENCIA_PLUX, ENLACE_PAGO, CREATED_AT, UPDATED_AT }) {
    this.ID_SOLICITUD = ID_SOLICITUD;
    this.ID_FUNDACION = ID_FUNDACION;
    this.ID_ADMIN = ID_ADMIN;
    this.ID_REPORTE = ID_REPORTE;
    this.MONTO = MONTO;
    this.DESCRIPCION = DESCRIPCION;
    this.ESTADO = ESTADO;
    this.FECHA_SOLICITUD = FECHA_SOLICITUD;
    this.FECHA_APROBACION = FECHA_APROBACION;
    this.FECHA_PAGO = FECHA_PAGO;
    this.OBSERVACIONES = OBSERVACIONES;
    this.REFERENCIA_PLUX = REFERENCIA_PLUX;
    this.ENLACE_PAGO = ENLACE_PAGO;
    this.CREATED_AT = CREATED_AT;
    this.UPDATED_AT = UPDATED_AT;
  }
}
