export class TransaccionPlux {
  constructor({ ID_TRANSACCION, ID_SOLICITUD, REFERENCIA_PLUX, ESTADO_PLUX, MONTO, MONEDA, METODO_PAGO, FECHA_TRANSACCION, DATOS_RESPUESTA, WEBHOOK_DATA, CREATED_AT, UPDATED_AT }) {
    this.ID_TRANSACCION = ID_TRANSACCION;
    this.ID_SOLICITUD = ID_SOLICITUD;
    this.REFERENCIA_PLUX = REFERENCIA_PLUX;
    this.ESTADO_PLUX = ESTADO_PLUX;
    this.MONTO = MONTO;
    this.MONEDA = MONEDA;
    this.METODO_PAGO = METODO_PAGO;
    this.FECHA_TRANSACCION = FECHA_TRANSACCION;
    this.DATOS_RESPUESTA = DATOS_RESPUESTA;
    this.WEBHOOK_DATA = WEBHOOK_DATA;
    this.CREATED_AT = CREATED_AT;
    this.UPDATED_AT = UPDATED_AT;
  }
}
